import { get } from './client'
import type { Listing, ListingVersion } from '../types'

// TODO: Replace with GET /api/v1/listings when endpoint is available
const listingsMock: Listing[] = [
  {
    id: 'listing-1',
    sellerId: 'seller-1',
    title: 'Квартира на ул. Пушкина',
    description: 'Просторная квартира в центре города',
    price: 45000000,
    totalAreaSqm: 120,
    districtId: 'hamovniki',
    floor: 5,
    totalFloors: 9,
    photosCount: 12,
    sellerType: 'OWNER',
    status: 'ACTIVE',
    score: 85,
    scoreBreakdown: [],
    enrichmentStatus: 'ENRICHED',
    districtMedianPriceSqm: 375000,
    priceDeviationPct: 2.1,
    districtDemandIndex: 8.5,
    competitorCount: 42,
    enrichedAt: '2026-04-20T10:30:00Z',
    createdAt: '2026-04-18T14:22:00Z',
  },
  {
    id: 'listing-2',
    sellerId: 'seller-2',
    title: 'Апартаменты на Арбате',
    description: 'Элегантные апартаменты с видом на улицу',
    price: 52000000,
    totalAreaSqm: 95,
    districtId: 'arbat',
    floor: 3,
    totalFloors: 7,
    photosCount: 18,
    sellerType: 'AGENCY',
    status: 'ACTIVE',
    score: 78,
    scoreBreakdown: [],
    enrichmentStatus: 'ENRICHED',
    districtMedianPriceSqm: 420000,
    priceDeviationPct: -1.5,
    districtDemandIndex: 7.2,
    competitorCount: 67,
    enrichedAt: '2026-04-19T09:15:00Z',
    createdAt: '2026-04-15T16:45:00Z',
  },
  {
    id: 'listing-3',
    sellerId: 'seller-3',
    title: 'Новая квартира в Пресненском',
    description: 'Современная новостройка',
    price: 38000000,
    totalAreaSqm: 110,
    districtId: 'presnya',
    floor: 8,
    totalFloors: 12,
    photosCount: 20,
    sellerType: 'DEVELOPER',
    status: 'ACTIVE',
    score: 71,
    scoreBreakdown: [],
    enrichmentStatus: 'ENRICHED',
    districtMedianPriceSqm: 350000,
    priceDeviationPct: 0.8,
    districtDemandIndex: 6.8,
    competitorCount: 51,
    enrichedAt: '2026-04-21T11:20:00Z',
    createdAt: '2026-04-16T13:10:00Z',
  },
  {
    id: 'listing-4',
    sellerId: 'seller-4',
    title: 'Квартира в Бирюлево',
    description: 'Доступный вариант для семьи',
    price: 22000000,
    totalAreaSqm: 85,
    districtId: 'biryulyovo',
    floor: 4,
    totalFloors: 5,
    photosCount: 8,
    sellerType: 'OWNER',
    status: 'ACTIVE',
    score: 54,
    scoreBreakdown: [],
    enrichmentStatus: 'PENDING',
    districtMedianPriceSqm: 260000,
    priceDeviationPct: 3.2,
    districtDemandIndex: 4.1,
    competitorCount: 34,
    enrichedAt: null as unknown as string,
    createdAt: '2026-04-22T10:00:00Z',
  },
]

export const listingsApi = {
  getById: (id: string) => get<Listing>(`/listings/${id}`),
  getVersions: (id: string) => get<ListingVersion[]>(`/listings/${id}/versions`),
  getContext: (id: string) => get(`/listings/${id}/context`),
  getRecommendations: (id: string) => get(`/listings/${id}/recommendations`),

  getAll: async () => {
    try {
      return await get<Listing[]>(`/listings`)
    } catch {
      return listingsMock
    }
  },
}
